### ISSUE TITLE
Taking a screenshot takes longer than it needs to

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#10]
It's all in the title.

**Comment by FayneAldan** [comment]
Upon doing some testing, I have found out that this is actually due to some bug in Citrus.

**Comment by FayneAldan** [comment]
Oh, wow... I just found out it's actually because GameYob takes a long time to take the screenshot, as it captures both screens... You should add a function to Citrus to only screenshot one screen (and maybe even with a file name, so it could save the screenshot under "(ROM file name)_(time).bmp").

**Comment by Steveice10** [comment]
Can you elaborate on why it taking time is an issue?

**Comment by FayneAldan** [comment]
Because it seems it takes more time trying to capture both screens, when it only needs to capture one (as the other one would be blank).

**Comment by Steveice10** [comment]
Yes, but why would that cause a crash? It doesn't take that long to capture the screens.

**Comment by FayneAldan** [comment]
[Quote: "Oh, wow... I just found out it's actually because GameYob takes a long time to take the screenshot, as it captures both screens..."](https://github.com/Steveice10/GameYob/issues/10#issuecomment-138340046)
If it helps, I'll change the title of the issue to reflect my recent discoveries.

**Comment by Steveice10** [comment]
Taking a screenshot takes a second or less. If it is taking longer, then it has crashed.

**Comment by FayneAldan** [comment]
It takes at least 10 seconds, but it doesn't crash. I'll try timing it now.

**Comment by Steveice10** [comment]
I'm able to see what you mean, but that definitely isn't the screenshot function operating as it should. It's not because I'm capturing both screens. (And by the way, the bottom screen format should be RGB565 at this point, so it's skipping the bottom screen anyway.)

**Comment by FayneAldan** [comment]
Well, if it takes less than a second for you, either file writing is slow on the N3DS with HB (assuming you use an original 3DS) or my microSD card is :hankey: and I never realized it. What I actually meant by capturing only one screen is to not have space for the other screen on the output in the first place. So, if the game is on the top screen, the output bmp is 400x240. 320x240 if on the bottom. This will at least serve as a partial "fix" for N3DS user (or my possibly :hankey: microSD Card) until a true fix is made.

As a side note, I think I remember the original GameYob by Drenn taking screenshots nearly instantly. Try seeing what he(?) did there.

**Comment by Steveice10** [comment]
No no, I'm definitely experiencing it. It's supposed to be quick, but its taking a while to write to file for some reason.

**Comment by FayneAldan** [comment]
```c++
FILE* file = fopen(fileStream.str().c_str(), "w");
if(file != NULL) {
    fwrite(header, 1, (std::streamsize) headerSize, file);
    fwrite(image, 1, (std::streamsize) imageSize, file);
    fclose(file);
}
```
That fixed it for me, in place of:
```c++
std::ofstream out;
out.open(fileStream.str());
if(out) {
    out.write((char*) header, (std::streamsize) headerSize);
    out.write((char*) image, (std::streamsize) imageSize);
    out.close();
}
```

**Comment by Steveice10** [comment]
Yeah, I just pushed that change myself. I also implemented your suggestion to screenshot only needed screens.

**Comment by FayneAldan** [comment]
All right. Also, I just want to make sure you see this:
https://github.com/Steveice10/GameYob/pull/9#issuecomment-138341214
