### ISSUE TITLE
Some bugs with GBS

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#11]
1. Sometimes stopping the music (by pressing B) as a note plays can cause the note to loop infinitely until a different song is started or B is pressed again. This is easy to replicate on the first non drum-roll note in the intro theme (not the title screen music) for Pokemon Red / Blue.
2. Resetting via button mapping doesn't trigger [gbsPlayerReset()](https://github.com/Steveice10/GameYob/blob/77ead0394dcdd351ee7f6271bd7ec67d2571646d/source/platform/common/gbsplayer.cpp#L10-L13), like it does [when resetting in the menu](https://github.com/Steveice10/GameYob/blob/77ead0394dcdd351ee7f6271bd7ec67d2571646d/source/platform/common/menu.cpp#L209-L212).
3. Every time you change the game screen while a GBS file is loaded, [a kitten dies](http://i.imgur.com/mBiDvdm.png).
4. Either way, the file info seems to be printing on the wrong screen regardless (according to the game screen setting).
5. Pressing the fast forward button shouldn't be allowed in this mode...

One other thing you could possibly do is make a GameBoy style interface for GBS files and have it render as if it was an GameBoy game (with frame support, etc.).

**Comment by Steveice10** [comment]
1. Not sure why that would happen as I'm completely resetting the APU on stop. I haven't looked into it in depth though, as it's fairly minor.
2-3. Should be fixed.
4. It's intended to be on the UI screen.
5. There's no reason to stop people from using it. It could be useful for something like fast forwarding to a favorite part of a song.

**Comment by FayneAldan** [comment]
As for one, try running the code twice. If that doesn't work, have it run a half/quarter second after the first run.
