### ISSUE TITLE
Graphical bug when run after blargSNES

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#14]
![Screenshot](http://i.imgur.com/vTcu8yF.png)

**Comment by StarWolf3000** [comment]
Only got this when not rebooting into the Homemenu after blargSNES. This may come from the awkward memory management of the HBL, not freeing up enough system resources upon closing an app.

Reboot into Homemenu and run it again, the glitch should be gone.

**Comment by FayneAldan** [comment]
That's the point... I think it's just the result of a weird graphics thing that blargSNES does.
