### ISSUE TITLE
Saving a state during BIOS boot results in an unloadable save state

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#15]

**Comment by FayneAldan** [comment]
This should be easily fixable simply by disabling the save state option while the BIOS is booting.

**Comment by Steveice10** [comment]
Cannot reproduce, works fine for me. I will reopen if you can provide me with an example of this happening.

**Comment by FayneAldan** [comment]
Sorry. It seems I missed something. Part of the crash is also the result of changing the BIOS settings.

**Comment by FayneAldan** [comment]
Are you going to reopen this...?

**Comment by Steveice10** [comment]
Sorry, I've been a bit busy. I'll reopen so I know to look into it when I get the chance.
