### ISSUE TITLE
text console black screen

### ISSUE THREAD

**Issue by neumaennl** [Steveice10/GameYob#17]
Hi, I just built ctrulib, citrus, and GameYob on my Ubuntu box using devkitARM without any source code changes, but unfortunately, when I start the GameYob I built on my n3DS XL, the menu is not displayed.
I can start the gameboy games just fine, though. I just have to do it "blind" because nothing is displayed on the lower screen.
Also, when I bring up the menu in game by pressing R, the bottom screen stays black. Any ideas?

**Comment by Steveice10** [comment]
Did not happen before hax 2.5. Likely that the xtrulib commit to fix it did not, or that it is a hax issue in the first place.
