### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by windwakr** [Steveice10/GameYob#18]
I'm using 1.0.7 on my 3DS as a .3ds file.

1. Pressing R opens the menu and immediately starts looping through the menu pages. This is quite annoying. I know I can tap on the screen to open the menu, and this won't be a problem, but pressing R is more convenient.

2. When pressing B to leave the menu, that B press is sent through to the game.

3. In the game Warlocked:
   * The objectives don't show up in the mission briefing screen. Just load up and select "play" twice, and you'll see the mission objective screen for the first mission. At the bottom of the screen, below the word "Objectives", there's supposed to be yellow text displaying the objectives. It doesn't show up in Gameyob.
   * The FPS drops when voices are played. It drops to the same level as the DS version did(down to ~50 at times ingame), which surprises me. I would think the 3DS has enough power to not slow down like that. There's a sound test in the options if you want a quick way to see this slowdown.

**Comment by Steveice10** [comment]
First two are fixed, third I'd recommend putting here instead: http://wiki.gbatemp.net/wiki/GameYob_3DS_Compatibility_List
