### ISSUE TITLE
Custom borders can't be selected

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#2]
BMP files don't appear on the file selector when selecting a border

**Comment by Steveice10** [comment]
Borders are PNG files.

**Comment by FayneAldan** [comment]
Why are the borders in the official GameYob border pack BMP files then?

**Comment by Steveice10** [comment]
Because those aren't for GameYob 3DS.

**Comment by FayneAldan** [comment]
Then where can I find borders for GameYob 3DS?

**Comment by Steveice10** [comment]
As of now, resaving those BMPs as PNGs should be fine. I just added support for varied sizes of borders, which will be in 1.0.2.
