### ISSUE TITLE
.cia isn't reproducing sound

### ISSUE THREAD

**Issue by GrayJack** [Steveice10/GameYob#22]
For some reason, after I installed the .cia for a test play and with my max sound opened and just there was no sound, but the sounds work just fine in the 3dsx version

**Comment by Steveice10** [comment]
You need to obtain a DSP firmware binary through whatever method suits you, and put it on your SD card at the path "/3ds/dspfirm.cdc". A more automated solution may be worked out later, but for now, that's pretty much your only option.
