### ISSUE TITLE
No default palette mode.

### ISSUE THREAD

**Issue by feraligatr** [Steveice10/GameYob#26]
On real GBC, the default palette for GB-mono (non SGB) games is "Dark Green", and I can use key combo to change palette on startup. [https://en.wikipedia.org/wiki/List_of_video_game_console_palettes#Game_Boy_Color](url)
In GameYob, when I set "BIOS Mode" to "GBC", there should be a way to follow this behavior rather than set palette manually.
But the "Colorize GB" option will always affect the palette.
- There're 14 options. "Auto" and "Classic Green" are not available on real GBC.
- "Off" actually means "Gray (Left+B)".
- "Auto" will use internal palette for some specific games, "Gray" for other games.

So there's no way to disable "Colorize GB" and let GBC Bios decide.

**Comment by Steveice10** [comment]
GBC BIOS colorization is not supported, with the "Colorize GB" option taking its place. If you want a specific palette, select it using that option.
