### ISSUE TITLE
Can't close app without opening ROM

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#3]
When using the 3DSX (along with IronHax), GameYob can't be closed without a ROM being open. No button combination seems to close GameYob in the file browser.

**Comment by Steveice10** [comment]
Interesting point, I can probably whip something up tomorrow. The file chooser menu already has an option to allow exiting by pressing B in the root directory, currently used for choosing BIOS and border files, so I might just adapt that for exiting from the ROM chooser.

**Comment by Steveice10** [comment]
Done, will be in 1.0.2.
