### ISSUE TITLE
Sound "pops" in Pokemon Crystal

### ISSUE THREAD

**Issue by twocows** [Steveice10/GameYob#30]
When playing Pokemon Crystal (and Pokemon Polished Crystal, which is a romhack of the former), the sound noticeably "pops." It sounds like it does this any time an instrument (soundbank? don't know the exact term) turns on, which can be several times per second.

I'm using an O3DS XL with GameYob 1.0.8 installed to my home screen. I can do some additional testing to see if this happens with other games if you want.

**Comment by Steveice10** [comment]
Sound popping is fixed in the latest git source. Of course, the latest git source doesn't run fast enough on an O3DS, but that's a different issue.
