### ISSUE TITLE
total newb question

### ISSUE THREAD

**Issue by Ninjistix** [Steveice10/GameYob#31]
Is there a guide somewhere on how to compile this? I'm new to trying to compile stuff that doesn't involve VS, or is there a nightly build anywhere? the latest release is like 101 commits behind master. I installed  devkitARM but kept getting errors when trying to run make, (was typing make gameyob.cia) if that helps, not sure if I'm missing something else.

**Comment by Steveice10** [comment]
You should be able to just run make with no arguments. Make sure that you used "git clone --recursive (repo)" when cloning to clone the buildtools submodule as well.

Do note, though, that the latest source doesn't run very well on the 3DS speed-wise. That's why the release build is so far behind.

**Comment by Ninjistix** [comment]
Dos that include the new 3ds xl?
