### ISSUE TITLE
Performance reggression since 1.08

### ISSUE THREAD

**Issue by purpasmart96** [Steveice10/GameYob#32]
I'm not sure if you are aware of this but using 1.08 is currently much faster then the current master branch. ~~I'm thinking the switch to citro3d and/or the switch to the dsp sound core might be one of the most likely culprits~~.

**Comment by Steveice10** [comment]
I'm already aware of this, and neither of those are the issue. It's simply because I did a lot of core rewrites and in the process boosted accuracy in some areas, with the consequence of reducing speed. I might come back to it someday, but have other priorities right now.

**Comment by purpasmart96** [comment]
Ok thank you.

**Comment by autofire372** [comment]
Latest commits seem to have helped this somewhat; Pokémon Crystal runs noticeably better (at or near 60 FPS on n3DS) than it did in most post-1.0.8 builds (around 40-45 FPS on same).

**Comment by autofire372** [comment]
If you have a n3DS, current source builds of GameYob run at full speed again. Performance still suffers on o3DS.

**Comment by legoj15** [comment]
Can confirm, Sonic Adventure 7 for the GBC (bootleg game lol) runs at full speed again

**Comment by Steveice10** [comment]
Yeah, I enabled the N3DS CPU speed-up. Still working on O3DS performance.
