### ISSUE TITLE
sound and scaler issues

### ISSUE THREAD

**Issue by lorecast162** [Steveice10/GameYob#33]
i have minor issues with sound on Zelda Oracle of Ages on Gameyob 3DS CIA, it's like lagging a bit...
also, i like to have crisp pixels on my GB/C games and so i use the Nearest scaler and Aspect zoom, and the pixels are kind of misplaced somewhere

**Comment by lorecast162** [comment]
just so you know, i tried with Retroarch Gambatte and the sound is totally ok, the crisp scaler isn't there so i can't proceed

**Comment by Steveice10** [comment]
Sound issues are fixed in the latest source, although the current source runs too slowly on the 3DS for a release. The nearest scaling is how it is, not much I can do to make it any better.
