### ISSUE TITLE
Cannot Name Cheats

### ISSUE THREAD

**Issue by gatekeeper1122** [Steveice10/GameYob#34]
Been trying to add cheat codes with names to my 3DS & it keeps displaying this number & invisible letters/numbers as you can see in the picture? can this be fixed?
![hgfvchbjn](https://cloud.githubusercontent.com/assets/16184353/22638737/61964c80-ec07-11e6-8757-b667563dcea9.jpg)

**Comment by Steveice10** [comment]
As of the latest source, cheats should now be in an ini formatted like so:

```
[name]
value=(value)
enabled=(0/1)
```
