### ISSUE TITLE
Feature request: Create cheats directly in Gameyob

### ISSUE THREAD

**Issue by My1** [Steveice10/GameYob#36]
especially for new3ds users it's a little bit annoying always having to get out the SD Card and put cheats on it, so it would be great if you could just directly create the cheats inside gameyob.

**Comment by neumaennl** [comment]
You don't have to take out the SD card. Just connect to the 3DS via WIFI using e.g. ftBrony

**Comment by Steveice10** [comment]
Currently no plans to add cheat creation within GameYob.

**Comment by My1** [comment]
honestly this is sad. is there a reason why?

**Comment by Steveice10** [comment]
Because it would be complex to implement on platforms without a proper keyboard (i.e. the WIP Switch frontend). Also, typing chests one-by-one on a tiny touch screen would probably be rather annoying.

**Comment by My1** [comment]
sure, the DS's touchscreen isnt big, sure but you wont need full qwertz either to enter a cheatcode as cheatcodes are in hex, at least that's how I remeber it.

also it depends a lot on the cheat on how annoying it is to enter it. a one-liner isnt that hard, also it would just add another way of using cheats. no one is saying to take away the method of using files and stuff.

**Comment by Steveice10** [comment]
You do have a point about hex making things a lot more simple... I'll reconsider it and see what I can come up with.

**Comment by Steveice10** [comment]
Actually, what about the cheat's name/description? Wouldn't that need a full keyboard?

**Comment by My1** [comment]
ouch, I totally forgot abut that. last time I even used my action replay on my DS (which iirc does have a smaller touchscreen that the 3DSes anyway) was long ago but I did so without issues.

**Comment by Steveice10** [comment]
Added in https://github.com/Steveice10/GameYob/commit/4890e2f0a0bc7bf10eec7b915c4e9b2d1e9ab07d

I was kind of hoping to avoid making it platform-specific, but it was the least complicated way. I suppose on the Switch side of things, libnx will hopefully eventually have software keyboard support.
