### ISSUE TITLE
Feature Request: All configs and saves under /3ds/data/GameYob

### ISSUE THREAD

**Issue by xadox-1st** [Steveice10/GameYob#37]
Since I am not able to compile it my self could you please change the save path of the config to _/3ds/data/GameYob/_ (Think its under _system_3ds.cpp_)

Maybe it is easy to change the save path for _.SAV_ of the games to _/3ds/data/GameYob/_, also.

**Comment by Steveice10** [comment]
Data has been moved to the folder the 3dsx is installed to.
