### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Remobit** [Steveice10/GameYob#39]
Sorry to bother, but can we get a new release out?
I can't figure out how to build it really and the current release is outdated to the point where it somehow disables the better cpu and memory of New 3ds (I found a build from early 2016 on GBATemp and it fixes that, so I assume it would be fixed if you pushed a new release) and I have to go into Rosalina every time to set it back.

**Comment by Steveice10** [comment]
The current release is too slow on the old 3DS.
