### ISSUE TITLE
Screen flickering issues (with borders?)

### ISSUE THREAD

**Issue by Steveice10** [Steveice10/GameYob#4]
As described here: http://gbatemp.net/threads/gameyob-3ds-gb-c-emu.372523/page-52#post-5642035

Added as a GitHub issue for organization purposes.

**Comment by Steveice10** [comment]
Seems like it might be gone? No further reports about it.

**Comment by FayneAldan** [comment]
Not fixed.

**Comment by Steveice10** [comment]
Can you provide details? A way to reproduce this? I haven't been able to reproduce this at all during my normal testing.

**Comment by FayneAldan** [comment]
I reproduced it when I was testing out several different borders, so it's possibly the result of rapid swapping borders... If I recall correctly, it starts taking effect if the border doesn't change when you change the border (from the file selector), in which case you'd then want to unpause the game.

**Comment by FayneAldan** [comment]
By the way, this MAY have been fixed with recent updates since I haven't encountered it lately...

**Comment by FayneAldan** [comment]
AFTER A SMALL AMOUNT OF TESTING, I have noticed that the screen flickering issues seem to occur when the system runs out of resources. This can especially be noticed if you rapidly switch between ROMs.
