### ISSUE TITLE
Hamtaro: Ham-Hams Unite! (U): Graphical garbage when text boxes appear

### ISSUE THREAD

**Issue by autofire372** [Steveice10/GameYob#43]
Garbage sprites appear whenever a text box is displayed. The garbage disappears when they are dismissed. Tested from current master.

[Screenshot](https://imgur.com/tcPeWhT)

**Comment by Steveice10** [comment]
Investigating now. Looks to be a bug in drawing the window layer.

**Comment by Steveice10** [comment]
Turned out to be a STAT register bug that led to the window layer not being turned off after the text box. Fixed in https://github.com/Steveice10/GameYob/commit/e58cbf0d976f37d4a505aff58fe570987feaa851
