### ISSUE TITLE
(Question) .cht files no longer work

### ISSUE THREAD

**Issue by autofire372** [Steveice10/GameYob#44]
As noted, .cht cheat lists from bgb don't work in this emulator anymore. Is this a bug, or did the cheat format change?

**Comment by autofire372** [comment]
As it turns out, cheat lists aren't working at all, even when properly formatted...

**Comment by Steveice10** [comment]
What happens when you try them?

**Comment by autofire372** [comment]
The "Manage Cheats" option remains unavailable (greyed out).

My example is a cheat file for Metroid 2:

```
[Debug Mode]
value=(0101A0D0)
enabled=(0)
```
They are supposed to be called (romname).ini, right?

**Comment by Steveice10** [comment]
Ah, remove the parentheses. In the example I gave, those were there to indicate that value and enabled were placeholders to fill in.

**Comment by autofire372** [comment]
Still not working.

**Comment by Steveice10** [comment]
Strange. I'll try to make sure to have the cheat format finalized and working by some time tomorrow, at the latest.

**Comment by Steveice10** [comment]
Not sure about how it was before, but I can confirm that the very latest commit has cheats working fine. I also decided to stick with the custom cheat format, as cheats from the RetroArch database for the games I was testing were of questionable quality.

Here's my test cheat file:
```
[Test]
value=0105EDD0
enabled=1
```

I named the file (ROM Name).cht, (e.g. "Pokemon Gold.gbc" would be matched with "Pokemon Gold.cht"), opened the cheats menu, enabled the cheat, and it worked fine.

**Comment by autofire372** [comment]
Nope; still broken on my end.

**Comment by autofire372** [comment]
Formatted exactly as you mentioned; still won't work.

**Comment by Steveice10** [comment]
File extension ".cht", same name as the ROM, and jn the same directory?

**Comment by autofire372** [comment]
Yep.

**Comment by Steveice10** [comment]
Alright. The only thing I can think of is that it could be a weird platform-specific quirk, as I was testing on my PC. I'll give it a shot on my 3DS tomorrow and see how that goes.

**Comment by Steveice10** [comment]
Okay, they definitely work on 3DS now. Turns out the 3DS did not like double-slashes in paths, while the PC version was perfectly fine with them.

**Comment by autofire372** [comment]
Yep, can confirm bug is squashed.

Incidentally, thanks for picking this emulator up again.
