### ISSUE TITLE
Feature Request: GBC IR Support

### ISSUE THREAD

**Issue by bennyman123abc** [Steveice10/GameYob#45]
Simple enough to implement for a person with 3DS homebrew experience; just receive and transmit basic IR data using the 3DS' IR transmitter/receiver. There are several games that use this functionality: Super Mario Bros. Deluxe, Pokemon Gen 2 games, and Donkey Kong Country, just to name a few. I could assist with testing on actual hardware (A real GBC) and would like to hear your feedback on this idea! :)

**Comment by bennyman123abc** [comment]
If you were to get this working, couldn't you also, theoretically, allow IR and link over the Switch's local area connection to allow it to work on both 3DS and Switch? I don't know if the 3DS has functions to allow for the use of its local area wireless, but if so, you could allow that for both 3DS and Switch as far as link goes. And I do believe that ctrulib supports IR connectivity, and quite simply too. It's just a matter of timing; though was an issue with the GBC when sending things over IR.

**Comment by Steveice10** [comment]
Yes, as you say, ctrulib supports IR connectivity and it is a matter of timing. However, it's precisely because it's a matter of timing that it's more complicated than simply passing the IR communications through to the 3DS APIs.

**Comment by bennyman123abc** [comment]
If I recall correctly, ctrulib supports commands to set timing and bitrate. I'm sure that could be used to assist the timing. Also, it seems that with the GBC, it only flashes the light and not in such a fast manner that it can't be detected by a standard camera, meaning that, as far as transmission, you could probably get away with initializing and deinitializing the IR module multiple times and not worry too much about timing there. I hope what I'm saying made sense.

**Comment by Drenn1** [comment]
I don't know if you've seen, but there's some experimental linking code in the master branch of GameYob DS that works by emulating both gameboys on both DS's (not the crappy version of linking in released versions). It has two modes, SGB linking (easier since only one system is emulated) and cable linking. I never got around to polishing it up enough for a proper release.

Theoretically it could work for IR too (no need to use the built-in IR sensor, just through wi-fi or local connections).

**Comment by bennyman123abc** [comment]
@Drenn1 The thing is, however, I want the IR support to use with an **ACTUAL** GBC. That's why I suggested I could test it on real hardware.

**Comment by Steveice10** [comment]
@bennyman123abc I actually looked into that possibility once, and I believe it's impossible due to differences in IR hardware specifications between the 3DS and the GBC.

**Comment by bennyman123abc** [comment]
Oh, that's sad. Well, it was worth an idea I suppose. What differences would've set them too much apart to make it impossible, however? I mean, they're both IR transmitters/receivers. There can only be but so much different that would make it impossible.
