### ISSUE TITLE
Games don`t launch on compiled build (dba7593)

### ISSUE THREAD

**Issue by vulpes-vulpeos** [Steveice10/GameYob#47]
Hello. I compiled build with latest commits (dba7593). Build and cia file were compiled/installed without any errors, but when I launch any rom it stuck on black screen. Emulator menu on bottom screen works without any problems.
Wanted to try to compile 1.0.8 to check if problem is on my side but could not do it with newer version of devkitpro (it requires citrus which I cannot compile).

Hardware: Ubuntu 18.04.1 running in VMware Fusion 10.1.1 on OSX 10.13.8 + New 2DS XL with 11.7.0 firmware and Luma 9.0.

**Comment by Boured** [comment]
It's a problem for me too, just wanting to let the Steveice10 know :P
