### ISSUE TITLE
SGB borders not working (release 1.0.8)

### ISSUE THREAD

**Issue by placeboyue** [Steveice10/GameYob#48]
I've tried all the possible combinations of settings and the SGB borders never show up.
The other issue open about this said it was fixed but apparently not.
I'm on an old 3DS using the latest release, haven't touched the .ini file at all

**Comment by Steveice10** [comment]
That's because they're in the latest source version, not the latest release. The latest source has its own performance problems on 3DS that led to there never being a release.
