### ISSUE TITLE
Shantae slows when on GBA Enhance mode

### ISSUE THREAD

**Issue by Julayla** [Steveice10/GameYob#49]
When I tried to play my copy of Shantae on my hacked 3DS using this emulator, I noticed that the game kinda starts slowing down. Is there any way to get that fixed?

**Comment by Steveice10** [comment]
Are you using the latest release or a build of the latest source? If it's the latter, you should use the latest release instead as the latest source has slowdown on 3DS.

Otherwise, I'm not really working on this right now since I hit a wall on performance vs accuracy.
