### ISSUE TITLE
Possibly more file selector color coding?

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#5]
Possibly have more color coding in the file selector (like how suspended ROMs show up as purple and folders as yellow). Possibly:
Game Boy ROMs = Keep white or gray ("monochrome")
Game Boy Color ROMs = Blue (to go along with the logo shown on the GBC boot screen)
Game Boy Sound (.gbs) files = Light blue
And maybe color code the Pokemon games as well.

**Comment by Steveice10** [comment]
I'd rather not clutter up the file selector with various colors. Colors are currently reserved for special entries, like directories and suspended games.

**Comment by FayneAldan** [comment]
Well, I'd kinda at least would like the .gbs file coloring so that I can mix in my GBS files with my ROMs more easily.

**Comment by Steveice10** [comment]
File type coloring is not planned. To be more precise, colors represent state, not type, where state can be directory, suspended, etc. I consider directory as a state and not a type as both directories and files (states) can be given extensions (type).
