### ISSUE TITLE
Bilinear filter option request, should not hinder performance!

### ISSUE THREAD

**Issue by Nashismo** [Steveice10/GameYob#51]
Hi Drenn/Steveice10:

(Request for Gameyob DS version, Drenn is inactive so I ask you Steveice10 to see this)

First of all let me tell you, your emulator is the most amazing thing ever created for the DS, so great that is even better than any emu on the 3DS to emulate the Gameboy.

I am sure you know that, but my request is simple. Would you add bilinear filter when scaling the resolution on this emulator?

See, the thing is this, the games when stretched look bad and wrong and not only that, but beacause NOT having a bilinear filter option, this creates noise when moving on a game horizontally!

This is the reason why Nintendo themselves use "Bilinear filtering" for their GB games on the VC. Not only the games look better (hiding the upscaling deformations) but also "bilinear filter" eliminates this noise when scrolling in games.

This is the only feature that stops your emulator from being perfect. The VC options on the 3DS by Nintendo lack so many options your emulators already has (colorisation of GB games, change button layout, SGB borders, etc).

This would be the world for me, and I think it would mean so much to everyone else with scaling problems.

My regards and please consider this option! Retroarch on 3DS has bilinear filter integrated by default (does NOT hinder performance), but the GB emulators are terrible there, leaps and bounds behind your emulator!

I humbly ask you for this, thank you with all my heart, 
Nashismo.

**Comment by Steveice10** [comment]
I haven't been working on this in quite a while, and even then I don't have anything to do with the DS version, so this isn't really the place for a DS version feature request.
