### ISSUE TITLE
Closing 3ds issue

### ISSUE THREAD

**Issue by Robomandude** [Steveice10/GameYob#6]
If you close the 3ds the screen turns off.  the emulation continues as evidenced by continuing sound, but if you open the 3ds again the screen stays black.

**Comment by FayneAldan** [comment]
That is a Homebrew Launcher bug, not a GameYob bug. You can prevent it by pressing the HOME button at ANY time after entering Homebrew mode, but it still doesn't pause emulation.

**Comment by Steveice10** [comment]
Indeed, not a GameYob issue.
