### ISSUE TITLE
Scaling borders

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/GameYob#7]
It would be kinda nice if borders would scale along with the game screen, rather than staying static.

**Comment by FayneAldan** [comment]
Have you noticed this yet?

**Comment by Steveice10** [comment]
Yes, although the idea is that a border would be designed for the with/without scaling. Not sure if I want to scale them, especially as that would mess up borders designed for scaled screens.

**Comment by FayneAldan** [comment]
You could always allow turning on or off the border scaling.

**Comment by Steveice10** [comment]
I'll consider it. I've been a bit busy lately, but I'll have some free time over the weekend.

**Comment by Steveice10** [comment]
Implemented, along with the ability to provide pre-scaled border images.

**Comment by FayneAldan** [comment]
I'm thinking about improving what you did with this in two ways:

1. Fix a text overflow in the menu created by the menu option you added.
2. Put all the border loading calls into a function for organization.

Expect a pull request sometime soon...
